<h1>Authors</h1>
<table class="table">
    <thead>
        <tr>
            <th>Avatar</th>
            <th>Name</th>
            <th>Email Address</th>
            <th>Actions</th>
        </tr>   
    </thead>
    <tbody>
        <?php foreach($this->authors as $author): ?>
        <tr>
            <td><img src="<?php echo $author->getAvatar(); ?>"></td>
            <td><?php echo $this->escapeHtml($author->getFullname()); ?></td>
            <td><?php echo $this->escapeHtml($author->getEmail()); ?></td>
            <td>
                <a href="<?php echo $this->url('content', ['controller' => 'author', 'action' => 'edit', 'id' => $author->getId()]) ?>">Edit</a>
                <a href="<?php echo $this->url('content', ['controller' => 'author', 'action' => 'delete', 'id' => $author->getId()]) ?>">Delete</a>
            </td>
        </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
